DROP TABLE POSTSHARE CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;
DROP TABLE GROUP1;
DROP TABLE GROUPJOIN CASCADE CONSTRAINTS;
DROP TABLE COMPANY;
DROP TABLE COMPANYFOLLOW CASCADE CONSTRAINTS;
DROP TABLE COMMENTHAS CASCADE CONSTRAINTS;
DROP TABLE RESOURCEATTACH CASCADE CONSTRAINTS;
DROP TABLE RESOURCEOWN CASCADE CONSTRAINTS;
DROP TABLE CONNECTIONS CASCADE CONSTRAINTS;

